apiVersion: apps/v1 
kind: Deployment
metadata:
  name: predict-marks 
  namespace: default
spec:
  replicas: 1 
  template:
    spec:
      containers:
      - name: app
        image: tensorflow/tensorflow:latest-devel-py3
        command: ["/bin/sh", "-c"]
        args:
         - echo "Start"
           git clone https://github.com/sourabh-burnwal/eks_training;
           cd eks_training;
           pip install -y keras;
           pip install -y flask;
           pip install -y numpy;
           pip install -y tensorflow;
           python server.py;
        ports:
        - containerPort: 8080 
          protocol: TCP
